repos:
- repo: local
  hooks:
  - id: rubocop
    name: Check Ruby style with rubocop
    description: Enforce Ruby style guide with rubocop
    entry: bin/rubocop-wrapper.sh
    language: script
    types: ['ruby']
    stages: [commit]
    verbose: true