repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        exclude: spec/support|.rubocop_todo.yml|config/credentials.yml.enc
    -   id: end-of-file-fixer
        exclude: config/credentials.yml.enc
    -   id: trailing-whitespace
- repo: local
  hooks:
  - id: rubocop
    name: Check Ruby style with rubocop
    description: Enforce Ruby style guide with rubocop
    entry: rubocop
    language: system
    args: [-a, --force-exclusion]
